name: ai_halls
description: "An app which generates worlds with AI."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0-180.3.beta <4.0.0"

dependencies:
  backstreets_widgets: ^0.11.0
  cupertino_icons: ^1.0.8
  dart_openai: ^5.1.0
  drift: ^2.18.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_soloud: ^2.0.2
  flutter_tts: ^4.0.2
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.24
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  drift_dev: ^2.18.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
flutter:
  uses-material-design: true
  assets:
    - assets/room_schema.json
